#%RAML 1.0
title: CPM Github API
description: CPM Github API. Used to Scatter-Gather Data from Github related to an individual repository
mediaType:
  - application/json
version: "1.0"
protocols:
  - HTTP
  - HTTPS
/github/{owner}/{repo}:
  get:
    displayName: Scatter Gather
    body: {}
    responses:
      "200":
        description: Pulls Data back From Github
        body:
          example:
            strict: true
            value:
              id: 290001605
              node_id: MDEwOlJlcG9zaXRvcnkyOTAwMDE2MDU=
              name: richTextInputFSC
              full_name: davidlarrimore/richTextInputFSC
              private: false
              owner:
                login: davidlarrimore
                id: 5623372
                node_id: MDQ6VXNlcjU2MjMzNzI=
                avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                gravatar_id: ""
                url: https://api.github.com/users/davidlarrimore
                html_url: https://github.com/davidlarrimore
                followers_url: https://api.github.com/users/davidlarrimore/followers
                following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                organizations_url: https://api.github.com/users/davidlarrimore/orgs
                repos_url: https://api.github.com/users/davidlarrimore/repos
                events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                received_events_url: https://api.github.com/users/davidlarrimore/received_events
                type: User
                site_admin: false
              html_url: https://github.com/davidlarrimore/richTextInputFSC
              description: This a duplicate of a peers RichTextInputFSC's repository used for Testing.....
              fork: false
              url: https://api.github.com/repos/davidlarrimore/richTextInputFSC
              forks_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/forks
              keys_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/keys{/key_id}
              collaborators_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/collaborators{/collaborator}
              teams_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/teams
              hooks_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/hooks
              issue_events_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/issues/events{/number}
              events_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/events
              assignees_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/assignees{/user}
              branches_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/branches{/branch}
              tags_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/tags
              blobs_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/blobs{/sha}
              git_tags_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/tags{/sha}
              git_refs_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/refs{/sha}
              trees_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees{/sha}
              statuses_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/statuses/{sha}
              languages_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/languages
              stargazers_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/stargazers
              contributors_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/contributors
              subscribers_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/subscribers
              subscription_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/subscription
              commits_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits{/sha}
              git_commits_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits{/sha}
              comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/comments{/number}
              issue_comment_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/issues/comments{/number}
              contents_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/contents/{+path}
              compare_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/compare/{base}...{head}
              merges_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/merges
              archive_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/{archive_format}{/ref}
              downloads_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/downloads
              issues_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/issues{/number}
              pulls_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/pulls{/number}
              milestones_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/milestones{/number}
              notifications_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/notifications{?since,all,participating}
              labels_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/labels{/name}
              releases_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/releases{/id}
              deployments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/deployments
              created_at: 2020-08-24T18:02:18Z
              updated_at: 2020-11-23T16:07:48Z
              pushed_at: 2020-11-23T16:07:46Z
              git_url: git://github.com/davidlarrimore/richTextInputFSC.git
              ssh_url: git@github.com:davidlarrimore/richTextInputFSC.git
              clone_url: https://github.com/davidlarrimore/richTextInputFSC.git
              svn_url: https://github.com/davidlarrimore/richTextInputFSC
              homepage: ""
              size: 18
              stargazers_count: 0
              watchers_count: 0
              language: JavaScript
              has_issues: true
              has_projects: true
              has_downloads: true
              has_wiki: true
              has_pages: false
              forks_count: 0
              mirror_url: null
              archived: false
              disabled: false
              open_issues_count: 0
              license: null
              forks: 0
              open_issues: 0
              watchers: 0
              default_branch: master
              temp_clone_token: null
              network_count: 0
              subscribers_count: 1
              commits:
                -
                  sha: d5f85079a4fe25e84e123c41430f365eb819f454
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OmQ1Zjg1MDc5YTRmZTI1ZTg0ZTEyM2M0MTQzMGYzNjVlYjgxOWY0NTQ=
                  commit:
                    author:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-23T16:07:40Z
                    committer:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-23T16:07:40Z
                    message: Update README.md
                    tree:
                      sha: 2ff9c60041ad51d50f46e59292a2438db3dc1bf9
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/2ff9c60041ad51d50f46e59292a2438db3dc1bf9
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/d5f85079a4fe25e84e123c41430f365eb819f454
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/d5f85079a4fe25e84e123c41430f365eb819f454
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/d5f85079a4fe25e84e123c41430f365eb819f454
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/d5f85079a4fe25e84e123c41430f365eb819f454/comments
                  author: null
                  committer: null
                  parents:
                    -
                      sha: 43b6518443bec6f5c4fd562a7b8d4e6585b25464
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/43b6518443bec6f5c4fd562a7b8d4e6585b25464
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/43b6518443bec6f5c4fd562a7b8d4e6585b25464
                -
                  sha: 43b6518443bec6f5c4fd562a7b8d4e6585b25464
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OjQzYjY1MTg0NDNiZWM2ZjVjNGZkNTYyYTdiOGQ0ZTY1ODViMjU0NjQ=
                  commit:
                    author:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-23T16:05:54Z
                    committer:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-23T16:05:54Z
                    message: New Version
                    tree:
                      sha: a4f9c6e23dda13e2155b13e2643c160ebbe6256a
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/a4f9c6e23dda13e2155b13e2643c160ebbe6256a
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/43b6518443bec6f5c4fd562a7b8d4e6585b25464
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/43b6518443bec6f5c4fd562a7b8d4e6585b25464
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/43b6518443bec6f5c4fd562a7b8d4e6585b25464
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/43b6518443bec6f5c4fd562a7b8d4e6585b25464/comments
                  author: null
                  committer: null
                  parents:
                    -
                      sha: ad796836fae552dd0a6e25b9fedc26a93a619b24
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ad796836fae552dd0a6e25b9fedc26a93a619b24
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/ad796836fae552dd0a6e25b9fedc26a93a619b24
                -
                  sha: ad796836fae552dd0a6e25b9fedc26a93a619b24
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OmFkNzk2ODM2ZmFlNTUyZGQwYTZlMjViOWZlZGMyNmE5M2E2MTliMjQ=
                  commit:
                    author:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-09T19:04:16Z
                    committer:
                      name: Dave Larrimore
                      email: dlarrimore@salesforce.com
                      date: 2020-11-09T19:04:16Z
                    message: Updated
                    tree:
                      sha: e5b14090615883984254769f06dcc43bec5e377a
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/e5b14090615883984254769f06dcc43bec5e377a
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/ad796836fae552dd0a6e25b9fedc26a93a619b24
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ad796836fae552dd0a6e25b9fedc26a93a619b24
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/ad796836fae552dd0a6e25b9fedc26a93a619b24
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ad796836fae552dd0a6e25b9fedc26a93a619b24/comments
                  author: null
                  committer: null
                  parents:
                    -
                      sha: ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                -
                  sha: ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OmJhOTljYTJmZmRkMGUyNTU5NmJlNGUxZmE5Y2JjMThiYjJmNTdmODE=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T19:26:30Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T19:26:30Z
                    message: adding orgInit.sh
                    tree:
                      sha: dac9ec2ad297fe8a46cdc625132ffdc319509ab2
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/dac9ec2ad297fe8a46cdc625132ffdc319509ab2
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents:
                    -
                      sha: 9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                -
                  sha: 9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OjliMmMwMDg5MGM0M2RjMDBjYzViMDU4ZTMzMTdjYzBhYTE0Yzg4NTY=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T14:52:50Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T14:52:50Z
                    message: updated package
                    tree:
                      sha: 4546359a8d84c9d2d59c4a37520ba0f531d9456e
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/4546359a8d84c9d2d59c4a37520ba0f531d9456e
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/9b2c00890c43dc00cc5b058e3317cc0aa14c8856
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/9b2c00890c43dc00cc5b058e3317cc0aa14c8856/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents:
                    -
                      sha: bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                -
                  sha: bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OmJmMWQ0ZmU4MThhMTllYTg4NDljMThmMWJkNjkyZDdhZmUzMzMxYmU=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T04:44:15Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T04:44:15Z
                    message: Post Package Release
                    tree:
                      sha: 5d78ca4ea75fb819b48f145b11827b501d79ce40
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/5d78ca4ea75fb819b48f145b11827b501d79ce40
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bf1d4fe818a19ea8849c18f1bd692d7afe3331be/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents:
                    -
                      sha: bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                -
                  sha: bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OmJkMmFhZTlmZDExODViNTU3MTEyOGU0YzJjNDFlYWZkZmFmY2JjNDQ=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T04:41:59Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-27T04:41:59Z
                    message: Updated Version
                    tree:
                      sha: 80cb37c723083e8f48b69f503d85936c16795c02
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/80cb37c723083e8f48b69f503d85936c16795c02
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bd2aae9fd1185b5571128e4c2c41eafdfafcbc44/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents:
                    -
                      sha: 4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                -
                  sha: 4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OjRiYTFlMWEwNWFkMzkyZjQ4ZGQwZThhMjk5OWQ2NjMxZWI5ZTc3MjU=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-24T18:22:24Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-24T18:22:24Z
                    message: Updated Project
                    tree:
                      sha: 93e20f5395756c2b855d75b9edbdab019a684079
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/93e20f5395756c2b855d75b9edbdab019a684079
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/4ba1e1a05ad392f48dd0e8a2999d6631eb9e7725/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents:
                    -
                      sha: 2f79555d13074b531c6e8e3983ca1851da13f411
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/2f79555d13074b531c6e8e3983ca1851da13f411
                      html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/2f79555d13074b531c6e8e3983ca1851da13f411
                -
                  sha: 2f79555d13074b531c6e8e3983ca1851da13f411
                  node_id: MDY6Q29tbWl0MjkwMDAxNjA1OjJmNzk1NTVkMTMwNzRiNTMxYzZlOGUzOTgzY2ExODUxZGExM2Y0MTE=
                  commit:
                    author:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-24T18:02:40Z
                    committer:
                      name: David Larrimore
                      email: davidlarrimore@gmail.com
                      date: 2020-08-24T18:02:40Z
                    message: first commit
                    tree:
                      sha: 6866e1b44d1f0a3d23e5b2689a66c4ab50d762bd
                      url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/trees/6866e1b44d1f0a3d23e5b2689a66c4ab50d762bd
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/git/commits/2f79555d13074b531c6e8e3983ca1851da13f411
                    comment_count: 0
                    verification:
                      verified: false
                      reason: unsigned
                      signature: null
                      payload: null
                  url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/2f79555d13074b531c6e8e3983ca1851da13f411
                  html_url: https://github.com/davidlarrimore/richTextInputFSC/commit/2f79555d13074b531c6e8e3983ca1851da13f411
                  comments_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/2f79555d13074b531c6e8e3983ca1851da13f411/comments
                  author:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  committer:
                    login: davidlarrimore
                    id: 5623372
                    node_id: MDQ6VXNlcjU2MjMzNzI=
                    avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                    gravatar_id: ""
                    url: https://api.github.com/users/davidlarrimore
                    html_url: https://github.com/davidlarrimore
                    followers_url: https://api.github.com/users/davidlarrimore/followers
                    following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                    gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                    starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                    subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                    organizations_url: https://api.github.com/users/davidlarrimore/orgs
                    repos_url: https://api.github.com/users/davidlarrimore/repos
                    events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                    received_events_url: https://api.github.com/users/davidlarrimore/received_events
                    type: User
                    site_admin: false
                  parents: []
              sfdx-project-dot-json:
                packageDirectories:
                  -
                    path: force-app
                    default: true
                    package: richTextAreaFSC
                    versionDescription: Finally Version 2!!!!
                    versionName: ver 0.3
                    versionNumber: 0.3.0.NEXT
                namespace: ""
                sfdcLoginUrl: https://login.salesforce.com
                sourceApiVersion: "47.0"
                packageAliases:
                  richTextAreaFSC: 0Ho3h000000KzLMCA0
                  richTextAreaFSC@0.1.0-1: 04t3h000004bdsNAAQ
                  richTextAreaFSC@0.2.0-1: 04t3h000004bdxnAAA
                  richTextAreaFSC@0.3.0-1: 04t3h000004bdyCAAQ
              tags:
                -
                  name: "3.0"
                  zipball_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/zipball/3.0
                  tarball_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/tarball/3.0
                  commit:
                    sha: bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                    url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/commits/bf1d4fe818a19ea8849c18f1bd692d7afe3331be
                  node_id: MDM6UmVmMjkwMDAxNjA1OnJlZnMvdGFncy8zLjA=
              release-latest:
                url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/releases/30224179
                assets_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/releases/30224179/assets
                upload_url: https://uploads.github.com/repos/davidlarrimore/richTextInputFSC/releases/30224179/assets{?name,label}
                html_url: https://github.com/davidlarrimore/richTextInputFSC/releases/tag/3.0
                id: 30224179
                author:
                  login: davidlarrimore
                  id: 5623372
                  node_id: MDQ6VXNlcjU2MjMzNzI=
                  avatar_url: https://avatars.githubusercontent.com/u/5623372?v=4
                  gravatar_id: ""
                  url: https://api.github.com/users/davidlarrimore
                  html_url: https://github.com/davidlarrimore
                  followers_url: https://api.github.com/users/davidlarrimore/followers
                  following_url: https://api.github.com/users/davidlarrimore/following{/other_user}
                  gists_url: https://api.github.com/users/davidlarrimore/gists{/gist_id}
                  starred_url: https://api.github.com/users/davidlarrimore/starred{/owner}{/repo}
                  subscriptions_url: https://api.github.com/users/davidlarrimore/subscriptions
                  organizations_url: https://api.github.com/users/davidlarrimore/orgs
                  repos_url: https://api.github.com/users/davidlarrimore/repos
                  events_url: https://api.github.com/users/davidlarrimore/events{/privacy}
                  received_events_url: https://api.github.com/users/davidlarrimore/received_events
                  type: User
                  site_admin: false
                node_id: MDc6UmVsZWFzZTMwMjI0MTc5
                tag_name: "3.0"
                target_commitish: master
                name: Version 3.0
                draft: false
                prerelease: false
                created_at: 2020-08-27T04:44:15Z
                published_at: 2020-08-27T14:40:09Z
                assets: []
                tarball_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/tarball/3.0
                zipball_url: https://api.github.com/repos/davidlarrimore/richTextInputFSC/zipball/3.0
                body: ""
          type: object
    securedBy: []
  uriParameters:
    owner:
      type: string
    repo:
      type: string
securedBy: []
